mkdir 'Misty  Larry Panels  CoNZealand'
wget 'https://stream.mux.com/hJor00V02L4VXkgZDMMyzYSXcrSaO7RKPZ/high.mp4' -O 'Misty  Larry Panels  CoNZealand/Reading  Misty  20200730.mp4'
wget 'https://stream.mux.com/NySEUCa900xPzysaZJnpxxF4G3dMmm58e/high.mp4' -O 'Misty  Larry Panels  CoNZealand/Open Chat  Misty  Larry  20200730.mp4'
wget 'https://stream.mux.com/8JchZgbhWuw00GzoWEsF1bk24zKD9PIV3/high.mp4' -O 'Misty  Larry Panels  CoNZealand/QA  Misty  Larry  20200730.mp4'
wget 'https://stream.mux.com/TfMvK5cbuSCHZw600r8dHK5wNn102FAohr/high.mp4' -O 'Misty  Larry Panels  CoNZealand/Bedtime Story  Misty  Larry  20200801.mp4'
wget 'https://stream.mux.com/b6C4k1lhuSC9CMbtf6X00300sRLLdflTTJ/high.mp4' -O 'Misty  Larry Panels  CoNZealand/Love Letter  Misty  Larry  20200731.mp4'
mkdir 'Film Festival'
mkdir 'Film Festival/Film Festival Block 01  CoNZealand'
wget 'https://stream.mux.com/TEzPDjf4ap00VwKgvnf1x00nafnFR4Q7zN/high.mp4' -O 'Film Festival/Film Festival Block 01  CoNZealand/01  The Divisible.mp4'
wget 'https://stream.mux.com/fiJ01XDg3bBnP1b15CNIEZzkZ773nu2Rg/high.mp4' -O 'Film Festival/Film Festival Block 01  CoNZealand/02  Osirika  Black Champagne.mp4'
wget 'https://stream.mux.com/Z9Qje9ewbXu5rv9wOh6fpvmnPREwoFuo/high.mp4' -O 'Film Festival/Film Festival Block 01  CoNZealand/03  From Shadow.mp4'
wget 'https://stream.mux.com/TUg00qmFZqo1IfIBKD1k7Kt302kFOv8JOw/high.mp4' -O 'Film Festival/Film Festival Block 01  CoNZealand/04  How Long.mp4'
wget 'https://stream.mux.com/5QJaD91Tfo9irrPhcURI01wKnnU9n02YG7/high.mp4' -O 'Film Festival/Film Festival Block 01  CoNZealand/05  The Electric Chair La silla eléctrica.mp4'
wget 'https://stream.mux.com/r3mhqO6M5srD8cFVxSuTQMXbkVm7bVyP/high.mp4' -O 'Film Festival/Film Festival Block 01  CoNZealand/06  The Widow.mp4'
wget 'https://stream.mux.com/LMYsZeG00bONfc0002x00EtyRkLVC8bC66Y2/high.mp4' -O 'Film Festival/Film Festival Block 01  CoNZealand/07  Revelation.mp4'
wget 'https://stream.mux.com/fyMszArBKImYKxRVVIZoU02QZVovPqmxR/high.mp4' -O 'Film Festival/Film Festival Block 01  CoNZealand/08  Choker.mp4'
wget 'https://stream.mux.com/ENqIn7q4TuhSnEhFMJ8tRTH4buIMhw4v/high.mp4' -O 'Film Festival/Film Festival Block 01  CoNZealand/09  A Purple Vision.mp4'
wget 'https://stream.mux.com/QEN029JnMBIDau27lsRvRJukRvoZqgBDb/high.mp4' -O 'Film Festival/Film Festival Block 01  CoNZealand/10  Moon Drops.mp4'
wget 'https://stream.mux.com/adeqEq66ODLJD5ixvzfucoHQeuLYrn3t/high.mp4' -O 'Film Festival/Film Festival Block 01  CoNZealand/11  The Quiet.mp4'
wget 'https://stream.mux.com/oaMCsQ9O0151DsAMxSjrV7Mkq402jxoOrr/high.mp4' -O 'Film Festival/Film Festival Block 01  CoNZealand/12  Gravity Hill.mp4'
wget 'https://stream.mux.com/2WrfiTbw5Hj01I2iDNDA86fbaXKUnts1E/high.mp4' -O 'Film Festival/Film Festival Block 01  CoNZealand/13  Oo La La.mp4'
wget 'https://stream.mux.com/Jv00pv1jrsTz2J02h01YvB8ietW01DQcZZZL/high.mp4' -O 'Film Festival/Film Festival Block 01  CoNZealand/14  Transmission.mp4'
wget 'https://stream.mux.com/9XW800a00cKypTZDaSwCCM2ZZSRLR3fUrI/high.mp4' -O 'Film Festival/Film Festival Block 01  CoNZealand/15  The Bargain.mp4'
wget 'https://stream.mux.com/E6IvybuVdC7O1lG00BqO2TTglqJMv00Xsk/high.mp4' -O 'Film Festival/Film Festival Block 01  CoNZealand/16  Honor Among Thieves.mp4'
wget 'https://stream.mux.com/abVGd4ZCJ1W00GDuJ1Etoceu2gk8x7Fql/high.mp4' -O 'Film Festival/Film Festival Block 01  CoNZealand/17  The Prospector.mp4'
wget 'https://stream.mux.com/i3ZuBHhT2oNSaUcU2W4JhU00HJ7bmDv01u/high.mp4' -O 'Film Festival/Film Festival Block 01  CoNZealand/18  Those Beautiful Moments.mp4'
wget 'https://stream.mux.com/F8dumxtFi02m9FU86jOn7ppxgfmGTBli00/high.mp4' -O 'Film Festival/Film Festival Block 01  CoNZealand/19  Skywatch.mp4'
mkdir 'Film Festival/Film Festival Block 02 CoNZealand'
wget 'https://stream.mux.com/6zXjinr9V01L7XNWudxoP2uEk7Lj02n6jC/high.mp4' -O 'Film Festival/Film Festival Block 02 CoNZealand/01  The 44 Scarves of Liza Minnelli.mp4'
wget 'https://stream.mux.com/AAeYD6ubvNyKGq6017Kd6WpgRAHgaKQJD/high.mp4' -O 'Film Festival/Film Festival Block 02 CoNZealand/02  The Kaleidoscope Guy at the Market.mp4'
wget 'https://stream.mux.com/1d2OFnKrtDVY2RplAvwaYlh9ek5YqnzT/high.mp4' -O 'Film Festival/Film Festival Block 02 CoNZealand/03  The Roads Most Traveled  Photojournalist Don Bartletti.mp4'
wget 'https://stream.mux.com/Hbd01HsP5ZYXSJVUhx7obHIWMhYhSsSTJ/high.mp4' -O 'Film Festival/Film Festival Block 02 CoNZealand/04  LES STROUD BIG YELLOW TAXI.mp4'
wget 'https://stream.mux.com/Le8jvogt2WFhH67rzZBafMqCExL00unoN/high.mp4' -O 'Film Festival/Film Festival Block 02 CoNZealand/05  Following the Lieutenant  Buffalo Soldiers of the Bicycle Corps.mp4'
wget 'https://stream.mux.com/KAFpm8DO2GNLtUiH4MSqSBQlXr00mztvC/high.mp4' -O 'Film Festival/Film Festival Block 02 CoNZealand/06  Older Than The Crown.mp4'
wget 'https://stream.mux.com/ok02l01NfyfvImxFXaXz9gmVNxPAICP8Rx/high.mp4' -O 'Film Festival/Film Festival Block 02 CoNZealand/07  iRony.mp4'
wget 'https://stream.mux.com/tWRgX1B700kyVho11InrXQ9LETEIBqE4I/high.mp4' -O 'Film Festival/Film Festival Block 02 CoNZealand/08  TOC.mp4'
wget 'https://stream.mux.com/M2sgJc0027GqYHdk00Fnll8v1s1qw6JOhN/high.mp4' -O 'Film Festival/Film Festival Block 02 CoNZealand/09  Blue and Malone.mp4'
wget 'https://stream.mux.com/UaREa2rP7Wvtj4wxdLmphpGfGVbfcBx9/high.mp4' -O 'Film Festival/Film Festival Block 02 CoNZealand/10  Catastrophe.mp4'
wget 'https://stream.mux.com/ZWY1zsh7SwtQ839qLF9BDHZFNLORHja02/high.mp4' -O 'Film Festival/Film Festival Block 02 CoNZealand/11  MADRID.mp4'
wget 'https://stream.mux.com/5b2cyP4N7T17tONAhGUQ6fvbhrpMSXaD/high.mp4' -O 'Film Festival/Film Festival Block 02 CoNZealand/12  CENICIENTA SWING.mp4'
wget 'https://stream.mux.com/WWS2ncNXLPTICEX58vDpZ02d02Unlkf01Rr/high.mp4' -O 'Film Festival/Film Festival Block 02 CoNZealand/13  The Moons Not That Great.mp4'
wget 'https://stream.mux.com/PJZnwSWkHjqIjuUs6OGmaCwFQ7vS6i9z/high.mp4' -O 'Film Festival/Film Festival Block 02 CoNZealand/14  One Last Monster.mp4'
wget 'https://stream.mux.com/NdkwJRPh5pt3OzQPWaga1R00UYaJoQycw/high.mp4' -O 'Film Festival/Film Festival Block 02 CoNZealand/15  Pressure.mp4'
wget 'https://stream.mux.com/KJd02aHUaCWESInQIHlkUVwrx029Kz8ZCK/high.mp4' -O 'Film Festival/Film Festival Block 02 CoNZealand/16  Mix.mp4'
wget 'https://stream.mux.com/fWUtwJHtglRJWlXUxR4nlt5fO01YrMZRg/high.mp4' -O 'Film Festival/Film Festival Block 02 CoNZealand/17  Echoes.mp4'
wget 'https://stream.mux.com/Q6GkX6toOhxNU9PoKSKRAYVS02Eo2m6Tp/high.mp4' -O 'Film Festival/Film Festival Block 02 CoNZealand/18  THE GREAT GREEN El Gran Verde.mp4'
wget 'https://stream.mux.com/rHsobq00sbKdphlfA7ZGZ6cchvrM01uWkv/high.mp4' -O 'Film Festival/Film Festival Block 02 CoNZealand/19  The Haunted Swordsman.mp4'
mkdir 'Film Festival/Film Festival Block 03  CoNZealand'
wget 'https://stream.mux.com/cIO3HfvBNvyUGW5XzGld2noob1IwX0000T/high.mp4' -O 'Film Festival/Film Festival Block 03  CoNZealand/01  Polarized  Brighter Day.mp4'
wget 'https://stream.mux.com/UqU2ial01snRI7OhxozJglN6XTpChlHyy/high.mp4' -O 'Film Festival/Film Festival Block 03  CoNZealand/02  Occupants.mp4'
wget 'https://stream.mux.com/Br001qDPnM01XyS9d02biiEs01Au5VfJZtM4/high.mp4' -O 'Film Festival/Film Festival Block 03  CoNZealand/03  Super Space Cowboy Rockstars Save the Universe Episode 1The Phantom Fellowship.mp4'
wget 'https://stream.mux.com/3XI9pHusXsBeKCAkaTMVHzohviSFZnYz/high.mp4' -O 'Film Festival/Film Festival Block 03  CoNZealand/04  Gon The Little Fox.mp4'
wget 'https://stream.mux.com/h9C5qRL9wM02sRfCxVIVk9K3F601oulUe5/high.mp4' -O 'Film Festival/Film Festival Block 03  CoNZealand/05  The Trouble With Cameos Who Knew Too Much.mp4'
wget 'https://stream.mux.com/PdZU2eBcSQ4irrty3bHSEjnVCF1zTpzD/high.mp4' -O 'Film Festival/Film Festival Block 03  CoNZealand/06  A New Generation.mp4'
wget 'https://stream.mux.com/3qqa02mAfoYoVyY6GKyNjd00qD45AIHDep/high.mp4' -O 'Film Festival/Film Festival Block 03  CoNZealand/07  Polter.mp4'
wget 'https://stream.mux.com/wtaKG5LV01kvVmm000241SgysNFtn9D01Emx/high.mp4' -O 'Film Festival/Film Festival Block 03  CoNZealand/08  The Peacemakers.mp4'
mkdir 'Film Festival/Film Festival Block 04  CoNZealand'
wget 'https://stream.mux.com/JjpXCLnEIq3tc1BjfPmCNzwjhV5OiiLw/high.mp4' -O 'Film Festival/Film Festival Block 04  CoNZealand/01  Strange Lights.mp4'
wget 'https://stream.mux.com/RxgZW99iDx01Xy4Bivd700yyUZF88tyBWA/high.mp4' -O 'Film Festival/Film Festival Block 04  CoNZealand/02  Do You Think of Me.mp4'
wget 'https://stream.mux.com/601MvH4T9tRLmkF501F91Gcw6ngs82SBZz/high.mp4' -O 'Film Festival/Film Festival Block 04  CoNZealand/03  The Last Thing to Die.mp4'
wget 'https://stream.mux.com/jxFHY7xP8hCqC57zvRv6hz4LVyuDYfrJ/high.mp4' -O 'Film Festival/Film Festival Block 04  CoNZealand/04  Your Last Day On Earth Tu último día en la Tierra.mp4'
wget 'https://stream.mux.com/u6x6WqGiljGrBBUUf00Ry01cE202ODeEL3g/high.mp4' -O 'Film Festival/Film Festival Block 04  CoNZealand/05  The Astronaut of God.mp4'
wget 'https://stream.mux.com/00XCH4nCT6mOqXmJXGGj4U42R8s9S01LcH/high.mp4' -O 'Film Festival/Film Festival Block 04  CoNZealand/06  Spirit A Martian Story.mp4'
wget 'https://stream.mux.com/etSrN1wJe00JMSmInGuDcxG5po01edL01Eo/high.mp4' -O 'Film Festival/Film Festival Block 04  CoNZealand/07  Nucleus.mp4'
wget 'https://stream.mux.com/Wd0001FNnIwTwBdf33MMt01400r9ueGn2Gna/high.mp4' -O 'Film Festival/Film Festival Block 04  CoNZealand/08  The Two Hundred Fifth.mp4'
wget 'https://stream.mux.com/nDrv2V32iEOZoVZs7N01FqRhGM8200uvfH/high.mp4' -O 'Film Festival/Film Festival Block 04  CoNZealand/09  Summon A Fiend.mp4'
wget 'https://stream.mux.com/rUfIW3qwJJ1iudMF5toxMTn02xwsSq8g02/high.mp4' -O 'Film Festival/Film Festival Block 04  CoNZealand/10  Interloper.mp4'
wget 'https://stream.mux.com/zQtstSgX800mpfgTey00WmiTLS9nEwicu7/high.mp4' -O 'Film Festival/Film Festival Block 04  CoNZealand/11  Gill.mp4'
wget 'https://stream.mux.com/MXIOOwv02uHdnxJLuMKOuXaJl3G5DLdxu/high.mp4' -O 'Film Festival/Film Festival Block 04  CoNZealand/12  Champagne.mp4'
wget 'https://stream.mux.com/tqbJiM1qfwEAC53FcqF2BIxVNuuxY1gE/high.mp4' -O 'Film Festival/Film Festival Block 04  CoNZealand/13  Encounters.mp4'
mkdir 'Film Festival/Film Festival Block 05  CoNZealand'
wget 'https://stream.mux.com/m702u8muOY023RoCKP00h8VR02RuzCHGSKu3/high.mp4' -O 'Film Festival/Film Festival Block 05  CoNZealand/01  Strowgers Revenge.mp4'
wget 'https://stream.mux.com/LjoPVJUJzqp7s89I6sHR3ppTOPQ5dMAT/high.mp4' -O 'Film Festival/Film Festival Block 05  CoNZealand/02  Its Hell Getting Old.mp4'
wget 'https://stream.mux.com/xjgshukd6wNHuFRgElSi02t01Xzu00tS3OJ/high.mp4' -O 'Film Festival/Film Festival Block 05  CoNZealand/03  Swipe.mp4'
wget 'https://stream.mux.com/gVkGWb3NuGy7dh01yuhOrUYz7004M01owIz/high.mp4' -O 'Film Festival/Film Festival Block 05  CoNZealand/04  From Inside.mp4'
wget 'https://stream.mux.com/nPboDeS9CnR602O2TT9CeKF1owwmgOvUQ/high.mp4' -O 'Film Festival/Film Festival Block 05  CoNZealand/05  Fused.mp4'
wget 'https://stream.mux.com/aeBjsH82tb9VUrwWDvFn14pQBft4OgiM/high.mp4' -O 'Film Festival/Film Festival Block 05  CoNZealand/06  Horizon.mp4'
wget 'https://stream.mux.com/uVfeDNu4WThnJx4MmIxxmUqJVwZ2LhHT/high.mp4' -O 'Film Festival/Film Festival Block 05  CoNZealand/07  Spiritual Practice.mp4'
wget 'https://stream.mux.com/thjQ5ksRO66nCs01XNqb6CFl1gTusvEn5/high.mp4' -O 'Film Festival/Film Festival Block 05  CoNZealand/08  In The Blood.mp4'
wget 'https://stream.mux.com/A02dkaRKsa6ewl3ZyBu49At02eIKWE87qU/high.mp4' -O 'Film Festival/Film Festival Block 05  CoNZealand/09  Reformed.mp4'
wget 'https://stream.mux.com/l01Q1SqsWvWJRmTxHLYQA012WDr8SqUBeN/high.mp4' -O 'Film Festival/Film Festival Block 05  CoNZealand/10  Tell.mp4'
wget 'https://stream.mux.com/f11dUSkzpCaVh5vcmP02ljNM2sLgN3i2d/high.mp4' -O 'Film Festival/Film Festival Block 05  CoNZealand/11  Kalo by Naoha.mp4'
wget 'https://stream.mux.com/t01wv9202ystHXHCU6geEwDfDF6gqbdqg6/high.mp4' -O 'Film Festival/Film Festival Block 05  CoNZealand/12  Transmission.mp4'
wget 'https://stream.mux.com/oaODkn6oEAqQvkHHzr00k6NaoIJXvC9Ni/high.mp4' -O 'Film Festival/Film Festival Block 05  CoNZealand/13  Moon Drops.mp4'
wget 'https://stream.mux.com/P3nXgYiq3U9wH6XNu01LtJbjcCmtsQy5I/high.mp4' -O 'Film Festival/Film Festival Block 05  CoNZealand/14  Oo La La.mp4'
wget 'https://stream.mux.com/S02S5FjdcuZDJpHY6BrMBUpfmYtUyeImS/high.mp4' -O 'Film Festival/Film Festival Block 05  CoNZealand/15  Spirit A Martian Story.mp4'
wget 'https://stream.mux.com/A6QsMeWjpVgnTpftfJlA4FR6QVnThAgi/high.mp4' -O 'Film Festival/Film Festival Block 05  CoNZealand/16  Gravity Hill.mp4'
wget 'https://stream.mux.com/QSgZ701jRaa01fm0292xRZVLtaD01o4b4G7h/high.mp4' -O 'Film Festival/Film Festival Block 05  CoNZealand/17  Skywatch.mp4'
wget 'https://stream.mux.com/hSNe9ha017s8A00WUa003w001KPqp021msduk/high.mp4' -O 'Film Festival/Film Festival Block 05  CoNZealand/18  The Haunted Swordsman.mp4'
wget 'https://stream.mux.com/Aifvuu6kuF1yyqDdqWT01U6hbdg3018b9A/high.mp4' -O 'Film Festival/Film Festival Block 05  CoNZealand/19  Your Last Day On Earth Tu último día en la Tierra.mp4'
wget 'https://stream.mux.com/q7LZMG8lFCj9WdhwLA5KR782peFkyASM/high.mp4' -O 'Film Festival/Film Festival Block 05  CoNZealand/20  Polter.mp4'
wget 'https://stream.mux.com/6ZWEx01dxn6KXPcfS9xY7cYmu01O01d4a2o/high.mp4' -O 'Film Festival/Film Festival Block 05  CoNZealand/21  Its Hell Getting Old.mp4'
mkdir '29 July  CoNZealand'
wget 'https://stream.mux.com/7p01LZdITS7GYK1YkK3VSdBIXFhRm8Ee1/high.mp4' -O '29 July  CoNZealand/Fantasy Today The Best of Recent Fantasy.mp4'
wget 'https://stream.mux.com/CidQJm02vuN00UKlr1B6tXo02jzvB1uvpvX/high.mp4' -O '29 July  CoNZealand/The Continuing Relevance and Popularity of The Lord of the Rings.mp4'
wget 'https://stream.mux.com/3zb00vr9d3xdJUQz3ZK8SO4PJcSJ3hA5S/high.mp4' -O '29 July  CoNZealand/Token Girl.mp4'
wget 'https://stream.mux.com/pgxa02Ng7UHy9stxWlOskxMe87auuhaTh/high.mp4' -O '29 July  CoNZealand/CoNZealand Opening Ceremony.mp4'
wget 'https://stream.mux.com/dX0238E02GJyzzhAj3iTzVP7fMrC1gs8h00/high.mp4' -O '29 July  CoNZealand/Shared Common Myths.mp4'
wget 'https://stream.mux.com/cAglFqcb01L3WPNXFTLVkdy01AV4L01Rmny/high.mp4' -O '29 July  CoNZealand/Is it Time for a Best OnlineInteractive Media Hugo.mp4'
wget 'https://stream.mux.com/u01LUYQrgF02eoxF9PGKadDnxYVxVGAaOS/high.mp4' -O '29 July  CoNZealand/My Favourite Things What I Always Remember about Game of Thrones.mp4'
wget 'https://stream.mux.com/CifXY2Lr02n4Cd8QaXrOkYNbAVcacIWAN/high.mp4' -O '29 July  CoNZealand/Reading Juliana Rew.mp4'
wget 'https://stream.mux.com/T6FlybN8Mp6aVIReNNkKYscfQZVvbq2O/high.mp4' -O '29 July  CoNZealand/Reading Stina Leicht.mp4'
wget 'https://stream.mux.com/dSolWlcHujiUZhSW8Q9i015irSe6ARdpN/high.mp4' -O '29 July  CoNZealand/The Art of the Review.mp4'
wget 'https://stream.mux.com/ty01yTP01CPVER7h3202JUdZxEe6QxHjhLH/high.mp4' -O '29 July  CoNZealand/Accessible Magic.mp4'
wget 'https://stream.mux.com/aVIJWewqK8RyUeQKh1VexltG95aWYbUC/high.mp4' -O '29 July  CoNZealand/Future Economics.mp4'
wget 'https://stream.mux.com/7006DEa0200vYDu01XaxgDyS00JmyOIqccix3/high.mp4' -O '29 July  CoNZealand/Reading JRH Lawless.mp4'
wget 'https://stream.mux.com/Yt8evWiKrRW21f013qfFB89V022zqMY00eo/high.mp4' -O '29 July  CoNZealand/Science Fantasy A Core Piece of the SFF World.mp4'
wget 'https://stream.mux.com/5waoZm5SO5GLBp01USBn1802rEvMETUe67/high.mp4' -O '29 July  CoNZealand/Novel vs Game Approaches to Narrative Fiction.mp4'
wget 'https://stream.mux.com/JT7FqGLpxtbrLmdzDR5c24SEBt00DLFVD/high.mp4' -O '29 July  CoNZealand/Chronology of Calendars.mp4'
wget 'https://stream.mux.com/Fd7700z1Dnf3JQs8nsfHBn43tAico63jx/high.mp4' -O '29 July  CoNZealand/Reading Maria Haskins.mp4'
wget 'https://stream.mux.com/zlgAbv00TqmpvILeQfvfIHKs8Uc9cQNTn/high.mp4' -O '29 July  CoNZealand/Reading Emma Osborne.mp4'
wget 'https://stream.mux.com/xRzSReP9ixW62KwHSPCbPPRViOkqrNqU/high.mp4' -O '29 July  CoNZealand/Reading Melinda Snodgrass.mp4'
wget 'https://stream.mux.com/abIllD9vTizfhWpWhxzP3qu02mHBMBSy9/high.mp4' -O '29 July  CoNZealand/Epidemics and Plagues in the Real World and in Fiction.mp4'
wget 'https://stream.mux.com/F02s6m2e2voc2ZzU8WOQFgEwSchNs3BHF/high.mp4' -O '29 July  CoNZealand/Small Press Leading the Way.mp4'
wget 'https://stream.mux.com/w3fFNFFarwp2xrG8o5uMcyhp9wJfsngq/high.mp4' -O '29 July  CoNZealand/The World of Independent Board Games Beyond DD.mp4'
wget 'https://stream.mux.com/pA2i5N5zo017Sa8uURrpGJVhPkcLVPCyP/high.mp4' -O '29 July  CoNZealand/Reading Ada Palmer.mp4'
wget 'https://stream.mux.com/d9HLtU02AxKvrUdbkOpT88Q3fg2b4Lct6/high.mp4' -O '29 July  CoNZealand/Reading Yugen Yashima.mp4'
wget 'https://stream.mux.com/o5TzoTcy3YX00pLiYfgFd02wra43nga9Qo/high.mp4' -O '29 July  CoNZealand/Can Living in a Small Space on Earth Prepare You for Living in Space.mp4'
wget 'https://stream.mux.com/Q933Rc00DD4HYtXZ1KIM3dgcKgEaDqr73/high.mp4' -O '29 July  CoNZealand/The Evolution of Fanzines.mp4'
wget 'https://stream.mux.com/tLq00x2bxnAigOm4k8nUnC5qV00S00lThG02/high.mp4' -O '29 July  CoNZealand/Reading SB Divya.mp4'
wget 'https://stream.mux.com/mbnQ1DQbZTArpURrEJf019p1S02Whc00x6k/high.mp4' -O '29 July  CoNZealand/Reading Mallory OMeara.mp4'
wget 'https://stream.mux.com/ka2SVa3ANumHFyjI015BMdGPkCoPxsHRn/high.mp4' -O '29 July  CoNZealand/Reading Umiyuri Katsuyama.mp4'
wget 'https://stream.mux.com/00L0200GsgMWFC24vnYvTLxKlbeT00YuG02pz/high.mp4' -O '29 July  CoNZealand/A Short Sharp Shock Horror in Few Words.mp4'
wget 'https://stream.mux.com/JJvSVObAVUepPlvZQ4s0002022mxw0052mGa/high.mp4' -O '29 July  CoNZealand/Writers on Writing Whats in a Name Characters in Fiction.mp4'
wget 'https://stream.mux.com/IWXZcjpklFJrNpN008Xy702AKcptHTxavi/high.mp4' -O '29 July  CoNZealand/Reading Mark English.mp4'
wget 'https://stream.mux.com/lR2BKna701nS00h01AoA00qc8XSSiHMXUxpH/high.mp4' -O '29 July  CoNZealand/Reading Sascha Stronach.mp4'
wget 'https://stream.mux.com/A3RCzGQSoY6AkHHC9RGNJwCbZmO9uRLK/high.mp4' -O '29 July  CoNZealand/Reading Jean Bürlesk.mp4'
wget 'https://stream.mux.com/7693DFdvzZzKuRIliyWJr3aISHxzXp81/high.mp4' -O '29 July  CoNZealand/Reading J J Mathews.mp4'
wget 'https://stream.mux.com/CILH9gaCpW1V7NEkwQumxfrol2A6TBuh/high.mp4' -O '29 July  CoNZealand/The Art of Kathleen Jennings.mp4'
wget 'https://stream.mux.com/01o3S9cMeezk9HUBvXl0202eqJDN800fjUpE/high.mp4' -O '29 July  CoNZealand/Reading Sultana Raza.mp4'
wget 'https://stream.mux.com/uCUEhb01301fSJLl01EKHJ8pErMOoXhn3zf/high.mp4' -O '29 July  CoNZealand/Planning and Attending Conventions in the Age of COVID19.mp4'
mkdir '30 July CoNZealand'
wget 'https://stream.mux.com/THokjUpV01W2Al4Fvv4tEgYF7fNiUJprQ/high.mp4' -O '30 July CoNZealand/Recent SF and Fantasy on TV Beyond the Usual Suspects.mp4'
wget 'https://stream.mux.com/h51EN1y5KAY6exz4P98qTPyySkfu4o6L/high.mp4' -O '30 July CoNZealand/Wild Cards Writing the Mosaic Novel.mp4'
wget 'https://stream.mux.com/Tz55yWZ9029wTGuyUtwDqp5I21HDz4AwY/high.mp4' -O '30 July CoNZealand/Climate Change Adaptation vs Resilience.mp4'
wget 'https://stream.mux.com/01k00ydfnaV01A3nnagvJzrhknFegNkrjCP/high.mp4' -O '30 July CoNZealand/Colossus Skynet or the Culture.mp4'
wget 'https://stream.mux.com/YedIqZ3C018NcYU9q3j4h8T5clAIkeJpc/high.mp4' -O '30 July CoNZealand/Justice in SF and Fantasy.mp4'
wget 'https://stream.mux.com/YvLEsj0101sIO02NnwFaj01DEqkMgSqji016P/high.mp4' -O '30 July CoNZealand/Special Effects in Feature Films The Evolution from Willis OBrien to Industrial Light and Magic and Weta.mp4'
wget 'https://stream.mux.com/1PkDVIGRxQYo1C01t5PauYVuEEaOrlkFr/high.mp4' -O '30 July CoNZealand/Reading Joe Haldeman.mp4'
wget 'https://stream.mux.com/yyyqYUNMupgSU7B67LRPrTSyjCS02AapM/high.mp4' -O '30 July CoNZealand/Reading Walter Jon Williams.mp4'
wget 'https://stream.mux.com/GDplc9nUur4Lml5fKtgPundyChqXAURd/high.mp4' -O '30 July CoNZealand/Staying Closer to Home Science Fiction in the Solar System.mp4'
wget 'https://stream.mux.com/QEYD02a9PtTy8MpueWCtIrvU3xZhnMwj2/high.mp4' -O '30 July CoNZealand/Lodestar Awards  Meet the Young Adult Award Finalists.mp4'
wget 'https://stream.mux.com/OPch4XlBfTd7QGWzslfR02mCpv7vMpiz01/high.mp4' -O '30 July CoNZealand/Collaborations Nightmare or Dream Gig.mp4'
wget 'https://stream.mux.com/02Eh35EADQQj7s7aZ7o6PGUgXCEW99LDe/high.mp4' -O '30 July CoNZealand/RetroHugos and the Sir Julius Vogel Awards Ceremonies.mp4'
wget 'https://stream.mux.com/pOvlja1pQymMXYc00wuY5wXdvhe7fCC02C/high.mp4' -O '30 July CoNZealand/Reading Mary Robinette Kowal.mp4'
wget 'https://stream.mux.com/Fvl02FnXTa3OvzSZSyYt4O3S9RlcZdfpS/high.mp4' -O '30 July CoNZealand/Reading Alex Acks.mp4'
wget 'https://stream.mux.com/00WStKZ34q02AfqKrRVICeSk8Pk7ZeYO0100/high.mp4' -O '30 July CoNZealand/Reading Illimani Ferreira.mp4'
wget 'https://stream.mux.com/IY8YJXtjQiOpkOmmV34TFtoCptMU59RY/high.mp4' -O '30 July CoNZealand/Reading Becky Chambers.mp4'
wget 'https://stream.mux.com/odVmFgqoXsALA02LKXtgeWZ013sfdUE9BX/high.mp4' -O '30 July CoNZealand/Modern SF Criticism.mp4'
wget 'https://stream.mux.com/ekSpVURh5eQacL79w4fQgDbKIQw5jJ57/high.mp4' -O '30 July CoNZealand/Music in SF and Fantasy.mp4'
wget 'https://stream.mux.com/siFpH4oQtCZ02Uya1gPlLEHgZXHQPUo1x/high.mp4' -O '30 July CoNZealand/Money and Currency for Fantasy Authorsmp4.mp4'
wget 'https://stream.mux.com/3UBlx33Jk4HeHAZpb4plJDoIaqphd163/high.mp4' -O '30 July CoNZealand/Reading Julie Czerneda.mp4'
wget 'https://stream.mux.com/GRWyYJi02YT01PxEMrHmrfFTq00nZEc5I4R/high.mp4' -O '30 July CoNZealand/Reading Andy Dudak.mp4'
wget 'https://stream.mux.com/u3zEGSvGeRRnwSrrm5M65eewTc021DiVV/high.mp4' -O '30 July CoNZealand/Reading Cindy Lynn Speer.mp4'
wget 'https://stream.mux.com/5O7iKRdt6aTKeSGl1sKwzD9joNedS8wV/high.mp4' -O '30 July CoNZealand/Reading Max Gladstone.mp4'
wget 'https://stream.mux.com/PoB00F74PKD02o2x02pOSrU47askW8Ipako/high.mp4' -O '30 July CoNZealand/Ray Bradbury Centennial.mp4'
wget 'https://stream.mux.com/t4d9xyileX58TzARtTSmaE2obg14I3et/high.mp4' -O '30 July CoNZealand/Cory Doctorow and Ada Palmer discuss censorship and information control.mp4'
wget 'https://stream.mux.com/j9YylChCcPiN00l6LHTSCaHIEElOn3kOi/high.mp4' -O '30 July CoNZealand/Reading Sarah Beth Durst.mp4'
wget 'https://stream.mux.com/FigcJC701W7fswdsHWgtgXkeQXCe6K3ZI/high.mp4' -O '30 July CoNZealand/Reading Curtis Chen.mp4'
wget 'https://stream.mux.com/6GRc5sJSxFiRNVAnrDGD01cWT9QTxHjV5/high.mp4' -O '30 July CoNZealand/Medicine in the Future From Surgery in Zero G to New Treatments for Disease.mp4'
wget 'https://stream.mux.com/clvTUlHToQdRwvSmHLP5n00CAaYLASIgy/high.mp4' -O '30 July CoNZealand/Covering Mercedes Lackey.mp4'
wget 'https://stream.mux.com/SL1DXbfzz35yyv2yIhph3s02IIZtcT00e5/high.mp4' -O '30 July CoNZealand/Publishing Spectrum from Indie to Traditional and the Hybrids Inbetween.mp4'
wget 'https://stream.mux.com/jO6vdyyV00KSviMrTD02inTKaLsFpbaufR/high.mp4' -O '30 July CoNZealand/Reading Kat Clay.mp4'
wget 'https://stream.mux.com/YlJ6uaU9CvN4a4Ct502rw4KnIQkKrWjy9/high.mp4' -O '30 July CoNZealand/Reading Charlie Jane Anders.mp4'
wget 'https://stream.mux.com/tCQVOGO9VEF2BhPo2NQfLJiis7KmCZSk/high.mp4' -O '30 July CoNZealand/Reading Jodi McAlister.mp4'
wget 'https://stream.mux.com/HlQyygqB7SLQX00L1sXWsZ02PFJGuF8at8/high.mp4' -O '30 July CoNZealand/New Zealand Authors on the International Stage.mp4'
wget 'https://stream.mux.com/B39vW14c01007JVuSybyFhsPi1FJ3z6rE9/high.mp4' -O '30 July CoNZealand/Nevertheless She Persisted The Explosion of the Heroine in the 50 Years Since Mia Havero.mp4'
wget 'https://stream.mux.com/5NmsFVAfLJnEN66pK1gmJuQJlDRRexpQ/high.mp4' -O '30 July CoNZealand/What to Do Till Your Ship Comes In.mp4'
wget 'https://stream.mux.com/IcYzDvpLSeIR02y65fKVb3prYjGRnuwUu/high.mp4' -O '30 July CoNZealand/Reading Simon Vance.mp4'
wget 'https://stream.mux.com/bmImbeqjwC02AJ00dpeQyNuvcwCvGOtZmT/high.mp4' -O '30 July CoNZealand/Reading Erin Wilcox.mp4'
wget 'https://stream.mux.com/4Zb2201hQNCezYP6dZ6X14HSdToH9RAdx/high.mp4' -O '30 July CoNZealand/Reading Daryl Gregory.mp4'
wget 'https://stream.mux.com/59KdVyFVAjIo00F00iqP7MlZgMHqnVSMhY/high.mp4' -O '30 July CoNZealand/Reading Taiyo Fujii.mp4'
wget 'https://stream.mux.com/mwJGfN02oNCHgi00i3hN1dPK01K6cFfSWxW/high.mp4' -O '30 July CoNZealand/SFF and Te Ao Māori.mp4'
wget 'https://stream.mux.com/9BgoWD5njTJeUFBIFbKmhW00KvloqFFAU/high.mp4' -O '30 July CoNZealand/The Golden Age of SF Movies SF Films of the 1950s and Early 1960.mp4'
wget 'https://stream.mux.com/01XblbqvsMnn7mT7NFzaBCNzP3fpyecgY/high.mp4' -O '30 July CoNZealand/Juggling for Writers Making Progress When Youve Got a Million Responsibilities.mp4'
wget 'https://stream.mux.com/Cc9CH12BZVgvOpM100xX00WmZ32UEm02FPD/high.mp4' -O '30 July CoNZealand/Reading Sean Williams.mp4'
wget 'https://stream.mux.com/1sYm4d3CukvjxcAww1rdh00SXwCli0155f/high.mp4' -O '30 July CoNZealand/Reading E J Beaton.mp4'
wget 'https://stream.mux.com/01t7nPAVMlJQ01VLmfuyuF1eelqrl022yeQ/high.mp4' -O '30 July CoNZealand/Reading Kyla Lee Ward.mp4'
wget 'https://stream.mux.com/BI01n1s6501DukwrVTtJ1XI2R02Efk2LUqC/high.mp4' -O '30 July CoNZealand/Reading Barbara Howe.mp4'
wget 'https://stream.mux.com/yhGVkvkWi1DgvJtRiSDXcjxtAYZTRWdE/high.mp4' -O '30 July CoNZealand/Translating Speculative Fiction Challenges and Exaltations.mp4'
wget 'https://stream.mux.com/B1lZ00d6S7kV02zoVcWFmAA7Vor7Ai8XOr/high.mp4' -O '30 July CoNZealand/Asian Women of Horror The Experience of Perpetual Otherness Through the Lens of Dark Fiction.mp4'
wget 'https://stream.mux.com/GnGX5kPJ1wMUtmEtuUgVuYMSa2SLOx8b/high.mp4' -O '30 July CoNZealand/On Afrofuturism.mp4'
wget 'https://stream.mux.com/AeM8nUfrQdZYTNqg02TeXZjNK44F9ufVg/high.mp4' -O '30 July CoNZealand/Reading Eileen Mueller.mp4'
wget 'https://stream.mux.com/wrML00Oj01PJLO87mukPivxu8kITIyzd1S/high.mp4' -O '30 July CoNZealand/Reading Eli K P William.mp4'
wget 'https://stream.mux.com/q1HNoZ00NIj1F7fCPU3RyzCVgp5wdaVrq/high.mp4' -O '30 July CoNZealand/Terraforming and Alien Life A Biochemists Perspective.mp4'
wget 'https://stream.mux.com/qs027ZpCoq1DjSCGOkEphwStEcDstph5m/high.mp4' -O '30 July CoNZealand/Spirits Abroad and At Home.mp4'
wget 'https://stream.mux.com/DctEI334EwUBkXlc4tJVjI9KbhEviX01R/high.mp4' -O '30 July CoNZealand/Not Long Before the End SF and the Economics of Resource Scarcity.mp4'
mkdir '31 July CoNZealand'
wget 'https://stream.mux.com/yVzY8mLzta4le8pZrrvCnjiSLV00fUOfv/high.mp4' -O '31 July CoNZealand/Brave New Revenue Stream.mp4'
wget 'https://stream.mux.com/gRj01h2XCPHQbj6iw4SzMxVs4BUtoVdf9/high.mp4' -O '31 July CoNZealand/Cover Art.mp4'
wget 'https://stream.mux.com/TAnXC1Dsx4ajw8ZcEKmRNyn5YAQgCelY/high.mp4' -O '31 July CoNZealand/Question Time 2 DisCon III.mp4'
wget 'https://stream.mux.com/ipHAn2FC5UNFRHuq02UN01YlgaQFpfsWXO/high.mp4' -O '31 July CoNZealand/2022 Worldcon Site Announcement.mp4'
wget 'https://stream.mux.com/fx7jPPAHsJ3UW8ewQc02z9QGNZ9WH3ICS/high.mp4' -O '31 July CoNZealand/Reading James Cambias.mp4'
wget 'https://stream.mux.com/AVOYdvLEFeyNQqwXbwQQ7w01W1xVGvc32/high.mp4' -O '31 July CoNZealand/Reading Peadar Ó Guilín.mp4'
wget 'https://stream.mux.com/uX9sbO2WFSPNWeF00xp01k01HypCzmICmVw/high.mp4' -O '31 July CoNZealand/Reading Brandon OBrien.mp4'
wget 'https://stream.mux.com/Ch9p7hAj3dq8f01e7VgjFLBG00cZbhovzv/high.mp4' -O '31 July CoNZealand/Dungeons and Dragons Still Going Strong.mp4'
wget 'https://stream.mux.com/twtrsBaFKiOyViqGi5uWHTwpPgBXiftD/high.mp4' -O '31 July CoNZealand/Marketing and Promoting Your Book.mp4'
wget 'https://stream.mux.com/ydZnQgNffkahNUcrYIeUVgOpx0202kPUCL/high.mp4' -O '31 July CoNZealand/Reading Alexandra Rowland.mp4'
wget 'https://stream.mux.com/abMDre5wKRv4ibl7MKbdB5n006Vn5J2eJ/high.mp4' -O '31 July CoNZealand/Getting Your Book Edited and Ready for Self Publishing.mp4'
wget 'https://stream.mux.com/00dK2DPQunbVxdg2lhEilMaCk0201PRUSTu/high.mp4' -O '31 July CoNZealand/Reading David Levine.mp4'
wget 'https://stream.mux.com/R7XZZGKqPZnqh5PLqAwOg2HLoe7KbZDe/high.mp4' -O '31 July CoNZealand/Reading Vida Cruz.mp4'
wget 'https://stream.mux.com/TBUAe01N2T00XydD51qWZKLqwhXuLV6kMr/high.mp4' -O '31 July CoNZealand/Reading Christine TaylorButler.mp4'
wget 'https://stream.mux.com/tS8fRedJoX00xKC8ClsBKib1EMzDvD6rN/high.mp4' -O '31 July CoNZealand/Reading Scott Edelman.mp4'
wget 'https://stream.mux.com/kBFQhvLXwTz02j1nulGGXjQjwyWjjVQoZ/high.mp4' -O '31 July CoNZealand/History and SF.mp4'
wget 'https://stream.mux.com/BGAYa3z7T9bApn2xbnjIkW34Ur4f502Dv/high.mp4' -O '31 July CoNZealand/Asimov at 100.mp4'
wget 'https://stream.mux.com/LSfpHBe4gWPTQzQ8yMtxBJxOXP1mLFSg/high.mp4' -O '31 July CoNZealand/Get to Know SFWA.mp4'
wget 'https://stream.mux.com/oY3l02xIrbZ02PP6S5ehYL7tjmOA8cFqpX/high.mp4' -O '31 July CoNZealand/Reading Mark Van Name.mp4'
wget 'https://stream.mux.com/pwOTC8kPsmpSmCHod9q6F81wMniRzC7f/high.mp4' -O '31 July CoNZealand/Reading Phoebe Wagner.mp4'
wget 'https://stream.mux.com/CpHH3PL5I02sajmMBkEyGOkDuY3Vsr6zD/high.mp4' -O '31 July CoNZealand/Reading Carrie Vaughn.mp4'
wget 'https://stream.mux.com/2DcoV02yDLCqEex1wgrTwE26UIoAwsrkF/high.mp4' -O '31 July CoNZealand/Killing Your Own Grandparent Time Travel in SF.mp4'
wget 'https://stream.mux.com/bz5rfz7017WIXNAKS4eY005jgqIk4YRng1/high.mp4' -O '31 July CoNZealand/Reading Gina Cole.mp4'
wget 'https://stream.mux.com/g02q9ybC003mtkdkM7Bv1efZvi01diDi01Mg/high.mp4' -O '31 July CoNZealand/Reading E Lily Yu.mp4'
wget 'https://stream.mux.com/YuYkS02ozjGVneyr6DMorjTEJ4MhUH3og/high.mp4' -O '31 July CoNZealand/My Favourite Anime.mp4'
wget 'https://stream.mux.com/qiIlECdPN7gryJQzYVo202Vn78UuS2mCH/high.mp4' -O '31 July CoNZealand/Mythology and Fantasy.mp4'
wget 'https://stream.mux.com/RvkD3h5ucob5UwLeO02iDe5NRSuAcrJCK/high.mp4' -O '31 July CoNZealand/How to Work with Editors.mp4'
wget 'https://stream.mux.com/Q8hhZ3TGKkilOb7601mmfV1Um7T021003x7/high.mp4' -O '31 July CoNZealand/Futures at the Worlds Edge.mp4'
wget 'https://stream.mux.com/uOO003Yig601SDf01lholUvqxls2e4y5mVI/high.mp4' -O '31 July CoNZealand/SF and Fantasy Comics and Graphic Novels.mp4'
wget 'https://stream.mux.com/QK3m00twGIMcbzn95n9GlXIrh02rsyZ5zU/high.mp4' -O '31 July CoNZealand/Magic Systems in Fantasy.mp4'
wget 'https://stream.mux.com/eYF00mVbW5DpGpKFO1g2RUEiMptEMdgoF/high.mp4' -O '31 July CoNZealand/Reading Deborah Munro.mp4'
wget 'https://stream.mux.com/jRn28e602UvgeHnw13NA3RLPu2htN00l4E/high.mp4' -O '31 July CoNZealand/Reading Sam Hawke.mp4'
wget 'https://stream.mux.com/wHQx9yxlCDtvI02Ukk802qAbbl1Vs47sUk/high.mp4' -O '31 July CoNZealand/Pew Pew What Would Realistic Space Battles Look Like.mp4'
wget 'https://stream.mux.com/LQs8cqDcVP1a4oX02s002vxh4pWEeEzQgt/high.mp4' -O '31 July CoNZealand/Costuming in a Big Group.mp4'
wget 'https://stream.mux.com/6l5iQ01oWp9J2R5t7dkkk4Px6NwZ682pj/high.mp4' -O '31 July CoNZealand/Reading Denika Mead.mp4'
wget 'https://stream.mux.com/cvpXAdzavbJVbPHlbYlGHqQ332Ekzblz/high.mp4' -O '31 July CoNZealand/Reading AJ Fitzwater.mp4'
wget 'https://stream.mux.com/iOoM8dxmIYFMToBDoNEOPR7m02Mi6Gyo3/high.mp4' -O '31 July CoNZealand/Reading Marlee Jane Ward.mp4'
wget 'https://stream.mux.com/GZBBxAq01N88ejx1FXPqneFGyX00scFRA02/high.mp4' -O '31 July CoNZealand/Is Cyberpunk Mainstream Now.mp4'
wget 'https://stream.mux.com/1tavHMlTU021O5TzmnTT4d93ciDEs2ygy/high.mp4' -O '31 July CoNZealand/SpecFicNZ Get To Know Us.mp4'
mkdir '01 August  CoNZealand'
wget 'https://stream.mux.com/4lfyMzoE3oqHkvcf02A1JDFNAXMEIGRBb/high.mp4' -O '01 August  CoNZealand/Before and After Tolkien Epic Fantasy.mp4'
wget 'https://stream.mux.com/E00aBcrn00oZYGDneEh5IiScm6tk01i1QVe/high.mp4' -O '01 August  CoNZealand/An Evening with Peadar  Farah.mp4'
wget 'https://stream.mux.com/L9VhLdBBZuud02Ap02jKVr01uod7byFD00iB/high.mp4' -O '01 August  CoNZealand/Reading Arkady Martine.mp4'
wget 'https://stream.mux.com/yeQsyUTZXx00EKFUpAzIsD8Tmh8Q9GTVl/high.mp4' -O '01 August  CoNZealand/Young Adult Fiction From the Page and From the Screen.mp4'
wget 'https://stream.mux.com/szZAejoRSfh9OiTIAW45ESb8JraBo00Kd/high.mp4' -O '01 August  CoNZealand/Constructed Language From Elvish to Esperanto to Dothraki to Belter.mp4'
wget 'https://stream.mux.com/W014KuHSlyMyGKkjvgOneADIU8R6O02YkO/high.mp4' -O '01 August  CoNZealand/Writing Fantasy and SF from the Margins.mp4'
wget 'https://stream.mux.com/j5uiWszU9X02AtepT75FNDxm02VXTyIAKa/high.mp4' -O '01 August  CoNZealand/Reading Frances Hardinge.mp4'
wget 'https://stream.mux.com/q00x01SJOlz8NaT01WMXbUw3AFEa5A0086vW/high.mp4' -O '01 August  CoNZealand/Reading Taru KumaraMoisio.mp4'
wget 'https://stream.mux.com/00JjirN1FT4zqAEXfBX1scEPirGyyu3Zz/high.mp4' -O '01 August  CoNZealand/Reading William Tracy.mp4'
wget 'https://stream.mux.com/SUpmRvzYM01KmQovW4WyEGnoABoh2FwoK/high.mp4' -O '01 August  CoNZealand/Reading Gregory Norman Bossert.mp4'
wget 'https://stream.mux.com/UXS02q200WcvZNCGQ02YzsTVQ01DDTA00q00S01/high.mp4' -O '01 August  CoNZealand/Reading Bren MacDibble.mp4'
wget 'https://stream.mux.com/pcpyCNvvbSikmNiNadGJFdyLAG01Bekav/high.mp4' -O '01 August  CoNZealand/Reading Whiti Hereaka.mp4'
wget 'https://stream.mux.com/6aL30202DcTiPbjJIFz2s7S2GqE7MsQaDg/high.mp4' -O '01 August  CoNZealand/Writing for Young Adults.mp4'
wget 'https://stream.mux.com/nh16XbWkAPT7aGreJE024Rg01e8BIg00FMD/high.mp4' -O '01 August  CoNZealand/Reading Stephen Dedman.mp4'
wget 'https://stream.mux.com/VTHXe3soogdHYa00V7bvHtbq8I6odYruH/high.mp4' -O '01 August  CoNZealand/Reading Catherine Lundoff.mp4'
wget 'https://stream.mux.com/4bQta02uD92M9NGMoiXy8EtpTty3tCn7s/high.mp4' -O '01 August  CoNZealand/Reading Alison Evans.mp4'
wget 'https://stream.mux.com/UbIguY2yO3TPiJmruc6aeBnTXtrLH7dh/high.mp4' -O '01 August  CoNZealand/Reading Angela Meyer.mp4'
wget 'https://stream.mux.com/sGaspyNUqrfTxMVJzOmCXVgVDuMJScMD/high.mp4' -O '01 August  CoNZealand/SF and Fantasy Video Games.mp4'
wget 'https://stream.mux.com/VEHNsu2On800o1KqHMdhL33kahyiNMqPS/high.mp4' -O '01 August  CoNZealand/Walking the Journey The Role of Nature and Place in Speculative Fiction.mp4'
wget 'https://stream.mux.com/WML3ADiXdwMq55KVrQP8dsj1oTTDkfNY/high.mp4' -O '01 August  CoNZealand/Good Work Questionable Creator.mp4'
wget 'https://stream.mux.com/8dtFaEawq00Pi4mn6N7P0054tLE51QHTa2/high.mp4' -O '01 August  CoNZealand/Reading Matthew Rotundo.mp4'
wget 'https://stream.mux.com/agjEPHpsLDxpHgIwnid1aKqeUD02N1ryC/high.mp4' -O '01 August  CoNZealand/Reading Darcie Little Badger.mp4'
wget 'https://stream.mux.com/lLVt1U424dSMmG1Srb3WgTZUBoZy8n024/high.mp4' -O '01 August  CoNZealand/Apocalypse Now and Then The Changing Nature of Apocalypse and PostApocalypse Fiction.mp4'
wget 'https://stream.mux.com/bkR6i2yqCk02CdN66BPfZkk9sn2Fw00kUH/high.mp4' -O '01 August  CoNZealand/The Future of EngineeringDesignManufacturing Influencing the World Influencing SF.mp4'
wget 'https://stream.mux.com/rfzQ01NaO01vcqJB01hLdDm7ZdFSp8SubN7/high.mp4' -O '01 August  CoNZealand/GOH  Tea with Rose Mitchell.mp4'
wget 'https://stream.mux.com/q00Qtetqw02FHy6Nxes6RT02yrhoHToHiBw/high.mp4' -O '01 August  CoNZealand/Reading Garth Nix.mp4'
wget 'https://stream.mux.com/pgiNwIhPsLkf7qYzEC1cl01shUi02puWSQ/high.mp4' -O '01 August  CoNZealand/Reading Amy AK DuBoff.mp4'
wget 'https://stream.mux.com/hggiy7CSPNZj9YO0000A5HgCwiSHX9a02n8/high.mp4' -O '01 August  CoNZealand/Reading Robinne Weiss.mp4'
wget 'https://stream.mux.com/PBbSsqBbfVWduuW4QtQ100iGrMI01isJZp/high.mp4' -O '01 August  CoNZealand/Reading Jenn Lyons.mp4'
wget 'https://stream.mux.com/fnfUW00YctoQjQiukZzNlef6pEJYFB5fw/high.mp4' -O '01 August  CoNZealand/Not Your Parents Space Opera.mp4'
wget 'https://stream.mux.com/tBMADTX9YFW301YSItxxWDXHEGbA28Fl9/high.mp4' -O '01 August  CoNZealand/From Kuttner to Pratchett Humour in Science Fiction and Fantasy.mp4'
wget 'https://stream.mux.com/YVe8APDWkjU01llF8OChHuVvpPzXncrEW/high.mp4' -O '01 August  CoNZealand/Novel Novella or Short Story Choosing the Right Length for Fiction.mp4'
wget 'https://stream.mux.com/MOd19t47m76vU4kLlaLpGCjN1ln94uGF/high.mp4' -O '01 August  CoNZealand/Reading Thoraiya Dyer.mp4'
wget 'https://stream.mux.com/s01ub9800KnXTpwB02DFYpyluLRiv9PBmv4/high.mp4' -O '01 August  CoNZealand/Reading Regina Wang.mp4'
wget 'https://stream.mux.com/FeniSd495WjDYGEPIe02F301iAam299wem/high.mp4' -O '01 August  CoNZealand/Reading Eugen Bacon.mp4'
wget 'https://stream.mux.com/gm1h1MEfQzL7rdNYEi3morPnBdKJ58I7/high.mp4' -O '01 August  CoNZealand/Reading Helen Marshall.mp4'
wget 'https://stream.mux.com/ZTiQYDkkGcC8RkZdozJ3GYjw47W01KBUM/high.mp4' -O '01 August  CoNZealand/Reading Maquel A Jacob.mp4'
wget 'https://stream.mux.com/Ryw2wF7P9jOeVEyZMI2gMYjpZZ7lklgn/high.mp4' -O '01 August  CoNZealand/Arthropods in Fiction.mp4'
wget 'https://stream.mux.com/kAn2BKrqHghwyQrst4FWBfoaICiTwKVB/high.mp4' -O '01 August  CoNZealand/Writers on Writing The Craft of Writing Alternate History.mp4'
wget 'https://stream.mux.com/h4WiOmBuedYA5vdVRXm00M010102Ukw1EXKd/high.mp4' -O '01 August  CoNZealand/Reading AJ Lancaster.mp4'
wget 'https://stream.mux.com/lVoUfnzh2J74cAZNlXsFVdauLVpA5qf4/high.mp4' -O '01 August  CoNZealand/Reading SL Huang.mp4'
wget 'https://stream.mux.com/m4gsupmkRON7WzG004OSEJ6TqI2k9hAW6/high.mp4' -O '01 August  CoNZealand/Reading David Hair.mp4'
wget 'https://stream.mux.com/JllUEm6nd00NeVerwNRW009Q995i02ts3mZ/high.mp4' -O '01 August  CoNZealand/Designing and Writing for Games.mp4'
wget 'https://stream.mux.com/MoY9zRlBjYU01tw02w7j9GicSAGUw81tPl/high.mp4' -O '01 August  CoNZealand/Becoming a Grownup The Bildungsroman in Stories for Young People.mp4'
wget 'https://stream.mux.com/Z02MpCMH902v3Oq02RYeS301VOeZYq5krdXO/high.mp4' -O '01 August  CoNZealand/Reading Yasser Bahjatt.mp4'
wget 'https://stream.mux.com/o6x0001avnV8RsbeLJknvjAZ6FQMmY0102wc/high.mp4' -O '01 August  CoNZealand/Reading Christopher Ruz.mp4'
wget 'https://stream.mux.com/sF02b9FZ4mGhb5UGsI02qVPDLTwHSpZxsw/high.mp4' -O '01 August  CoNZealand/Reading HG Parry.mp4'
wget 'https://stream.mux.com/IfeU6LnCK02988fOFXasDw75eGETkcrmW/high.mp4' -O '01 August  CoNZealand/Chinese Short Fiction.mp4'
wget 'https://stream.mux.com/aElbhZ02vzHL600HTBj2x3MA02HIr9llboL/high.mp4' -O '01 August  CoNZealand/Intersection of Science Fiction and Technology in Japan.mp4'
wget 'https://stream.mux.com/LINT1Vumz3wMRdAyOE4h4vQPQeSP3rSD/high.mp4' -O '01 August  CoNZealand/Whats Different about New Zealand Comics.mp4'
wget 'https://stream.mux.com/1DpkJTHKaUXYtzw3r3SzqfATZFLxW3tS/high.mp4' -O '01 August  CoNZealand/SF Movies that Look Great but Are Awful.mp4'
wget 'https://stream.mux.com/6ObWS9whT601FMRIHgjgZlPw8W702AOo400/high.mp4' -O '01 August  CoNZealand/Gravity Awards Ceremony.mp4'
wget 'https://stream.mux.com/tjJ12oOzJ1vHKtaiEv1ALxXPdRrB5Al2/high.mp4' -O '01 August  CoNZealand/Contemplating an International Move.mp4'
wget 'https://stream.mux.com/NftFsfEdv5VVt4be4NUh8Rp6h7tE4Nzx/high.mp4' -O '01 August  CoNZealand/Monsters in the Garden a New Zealand SFF Anthology.mp4'
wget 'https://stream.mux.com/iv01e1IvwXs4WBqq7RrZNI01JyNe01HjM900/high.mp4' -O '01 August  CoNZealand/Nordic Fantastic Literature.mp4'
wget 'https://stream.mux.com/W0016ZIFgreHRn01tMvF600Y2Xu4UNAro9Q/high.mp4' -O '01 August  CoNZealand/Reading Judith Huang.mp4'
mkdir '02 August  CoNZealand'
wget 'https://stream.mux.com/d1NcD02CZhfLVWW3SWNRYJ00eXoj77R02zd/high.mp4' -O '02 August  CoNZealand/Recent Scientific Breakthroughs  Whats Hot.mp4'
wget 'https://stream.mux.com/QZvsm1lMxxhPhO6dnvtSW4znbhGE7HWj/high.mp4' -O '02 August  CoNZealand/Artists I Want People to Know About.mp4'
wget 'https://stream.mux.com/D9D3HsNSGtcl4TlcT92Yy00pm3pBxnMu1/high.mp4' -O '02 August  CoNZealand/Reading Fiona Moore.mp4'
wget 'https://stream.mux.com/jcZQ02thzmquIh1i01KiSUAFPKEA8tcp3j/high.mp4' -O '02 August  CoNZealand/Reading Karl Schroeder.mp4'
wget 'https://stream.mux.com/00Y5YzEPCKA6Je8c1Bn4Bh7W1DfHq8tIB/high.mp4' -O '02 August  CoNZealand/From Page to Screen Screenwriting 101.mp4'
wget 'https://stream.mux.com/yzKKrkz5wvUNXmtXhWJc4fa8Cf93SISa/high.mp4' -O '02 August  CoNZealand/The History of the Book.mp4'
wget 'https://stream.mux.com/yPwCy4c17wNJXWK4XbFJbKDKZnUUtWW4/high.mp4' -O '02 August  CoNZealand/Fairy Tales and Fantasy.mp4'
wget 'https://stream.mux.com/L8luCdnSklcxr7GYtU017EHtBKgpL1voE/high.mp4' -O '02 August  CoNZealand/Reading C Stuart Hardwick.mp4'
wget 'https://stream.mux.com/Zjh02RbKV01f2nWbMzVR9kHXxaxtnWGehk/high.mp4' -O '02 August  CoNZealand/Reading Sally McLennan.mp4'
wget 'https://stream.mux.com/IkFmUsQkj2YW00uwtvdMsbq1apPoXLzlB/high.mp4' -O '02 August  CoNZealand/Reading Arwen Curry.mp4'
wget 'https://stream.mux.com/ojbpPoodRp5dRIHR4EbxGjklm6cp1i0101/high.mp4' -O '02 August  CoNZealand/Reading Dan Rabarts.mp4'
wget 'https://stream.mux.com/7AJ56qUV702LB9YC6Y9Th9eAxWCudTQZL/high.mp4' -O '02 August  CoNZealand/Military SF Getting It Right.mp4'
wget 'https://stream.mux.com/3rfOsLWW1sZ8s7rZ6tNRSNY2AD4DGMwj/high.mp4' -O '02 August  CoNZealand/The Day After Tomorrow Near Future SF.mp4'
wget 'https://stream.mux.com/01qMo9m5PNbdZb8peFpJ1d2XRdpnwLp1D/high.mp4' -O '02 August  CoNZealand/Speculative Poetry 2020 The Rhyme of the SF Mariner.mp4'
wget 'https://stream.mux.com/WPUpMUVn41XTKm8cOGuMdX02VCwckbBcB/high.mp4' -O '02 August  CoNZealand/Reading Courtney Schafer.mp4'
wget 'https://stream.mux.com/OexEeW67oridPMv4y501RFtsmmat1v01dT/high.mp4' -O '02 August  CoNZealand/Reading Cat Rambo.mp4'
wget 'https://stream.mux.com/xHMkwUiQa9U018udu012dcjUNT8bXSTCmn/high.mp4' -O '02 August  CoNZealand/Reading Naomi Kritzer.mp4'
wget 'https://stream.mux.com/k2e02OQgEpLdP8TfGrxaTC9jswmtziC02E/high.mp4' -O '02 August  CoNZealand/In Conversation Gary K Wolfe and Joe Haldeman.mp4'
wget 'https://stream.mux.com/raFetvO5x5gfUXHDvTGdVQ6Q7ELepfnR/high.mp4' -O '02 August  CoNZealand/Comics and Manga in the 21st Century.mp4'
wget 'https://stream.mux.com/iRbVdtZ6wt01R1eN75YKpylsEuHgB2eAA/high.mp4' -O '02 August  CoNZealand/In Space No One Can See You Hide the Evidence Crimes in Space.mp4'
wget 'https://stream.mux.com/N8yjIQhzoBxIiSOaFy9Fc02H50202Pxd701n/high.mp4' -O '02 August  CoNZealand/Reading LJ Kendall.mp4'
wget 'https://stream.mux.com/BU1Sz01UYR5deaCNgGEOKAyccDIVKa401O/high.mp4' -O '02 August  CoNZealand/Reading Amanda Bridgeman.mp4'
wget 'https://stream.mux.com/2KnLR622sku19a6SxNJj4gP3M3SY00I027/high.mp4' -O '02 August  CoNZealand/Reading Prema Arasu.mp4'
wget 'https://stream.mux.com/tbOkzL3BeHj7DjLy01BLjndJjj4sXvRdg/high.mp4' -O '02 August  CoNZealand/The Best of the Rest 2019 Novels that Werent Nominated for a Hugo.mp4'
wget 'https://stream.mux.com/hB029qI4l8jxDZgcSTJ9QU7HxvQgwlPW3/high.mp4' -O '02 August  CoNZealand/Virtual Conventions and Conferences.mp4'
wget 'https://stream.mux.com/2LdBkD44gdGO32fWKT96EIpz9zwJgmkl/high.mp4' -O '02 August  CoNZealand/Reading Sarah Gailey.mp4'
wget 'https://stream.mux.com/MSopMqm9LxWO02b7BnqCby9vRKaPWapu00/high.mp4' -O '02 August  CoNZealand/Reading Dylan Horrocks.mp4'
wget 'https://stream.mux.com/id6yYZ9tdFkUCTj1cQbt00yrgqVilnYrp/high.mp4' -O '02 August  CoNZealand/Celebrating the Greats.mp4'
wget 'https://stream.mux.com/RG8BOQSYab6b6YaWBv4R2FX01xLrErPz2/high.mp4' -O '02 August  CoNZealand/Reading Cory Doctorow.mp4'
mkdir 'Track 01  CoNZealand'
wget 'https://stream.mux.com/dzvFMH3KU02wwLC6H3JM02NgfCTHPEtVqJ/high.mp4' -O 'Track 01  CoNZealand/SF and Fantasy of Australia.mp4'
wget 'https://stream.mux.com/1KdpAjKBUo597g7cg5JcldE7F25xnlZ8/high.mp4' -O 'Track 01  CoNZealand/Who What When andor Where Inspired You.mp4'
wget 'https://stream.mux.com/ASj01OZi00kOYxeVXtVBoZNNWP4eN8rSWY/high.mp4' -O 'Track 01  CoNZealand/The Atlanta Radio Theatre Presents Omnilingual and other SF Radio Plays.mp4'
wget 'https://stream.mux.com/yQx83PJzJSY4gU5T9X1VHwXhuI6ysK81/high.mp4' -O 'Track 01  CoNZealand/My Favourite Things What I Always Remember About Jacksons Lord of the Rings Trilogy.mp4'
wget 'https://stream.mux.com/rVqcPyWvK014WGOOjaQFQTbp8aYatvsvp/high.mp4' -O 'Track 01  CoNZealand/56 Years to Air ST SNW.mp4'
wget 'https://stream.mux.com/UyUhuiuolQRxnNDlk8RoqC59P1cSpezH/high.mp4' -O 'Track 01  CoNZealand/Japanese Science Fiction.mp4'
wget 'https://stream.mux.com/JmDnNRoyC72MmJj9gE6S9D3LlHFlWXjP/high.mp4' -O 'Track 01  CoNZealand/Representing the Other.mp4'
wget 'https://stream.mux.com/XpEtCJHR01rN1yID3ssjiftHy9YBUFIrg/high.mp4' -O 'Track 01  CoNZealand/Are We Living in a Simulation.mp4'
wget 'https://stream.mux.com/EVYK8sll3nnfyarVdkfg9yHOV96sXhLe/high.mp4' -O 'Track 01  CoNZealand/Come Time Travel with Me  1965.mp4'
wget 'https://stream.mux.com/u9ksLVElfjSCXa2AguDHBpGbwoROsZ6X/high.mp4' -O 'Track 01  CoNZealand/The Future Is Female Women SF Writers from Mary Shelley to Ursula Le Guin and Octavia Butler.mp4'
wget 'https://stream.mux.com/DeLymcUg021m3zhZd6ueo4zszUoGpKR4y/high.mp4' -O 'Track 01  CoNZealand/The Timeless Child and the Evolving Canon of Doctor Who.mp4'
wget 'https://stream.mux.com/x01Njysw6OkokLz5jHucpUXU00H5WV01b3g/high.mp4' -O 'Track 01  CoNZealand/Modern Short SF and Fantasy.mp4'
wget 'https://stream.mux.com/PeYfp2oXFD1CxaBlWrfEQA2h24xnE3vR/high.mp4' -O 'Track 01  CoNZealand/Stunts in SF Films and TV Shows.mp4'
wget 'https://stream.mux.com/2JIMtH6MdbLqkJcX6OTAweMVEMe00HQgJ/high.mp4' -O 'Track 01  CoNZealand/A Chat with Bob and George.mp4'
wget 'https://stream.mux.com/gUOLYq6avCyUrghROWi3mRuXoNs0000mnS/high.mp4' -O 'Track 01  CoNZealand/Sandman at 30 The Enduring Influence of Neil Gaimans Creation.mp4'
wget 'https://stream.mux.com/h15buqb01Gmvc6pX2pT023phIo9hR5M641/high.mp4' -O 'Track 01  CoNZealand/How to End the World on 500.mp4'
wget 'https://stream.mux.com/BVdCc7xzRw9XjYjWDRqqKYmtx8y7aZ02l/high.mp4' -O 'Track 01  CoNZealand/Trends How they Affect Tropes in FSF.mp4'
wget 'https://stream.mux.com/srfVvZoUtXQa1JzlCO4mYRiEPqTkMRAP/high.mp4' -O 'Track 01  CoNZealand/COVID19 A Great Filter.mp4'
wget 'https://stream.mux.com/M2OdAMyxyPgb60100EgTpgM007rPqXKRMDK/high.mp4' -O 'Track 01  CoNZealand/Ask a Scientist.mp4'
wget 'https://stream.mux.com/AKgLH0247g00s3thFxSOkmj01TiTH2WwijA/high.mp4' -O 'Track 01  CoNZealand/A Fireside Chat with Artist Guest of Honour Greg Broadmore.mp4'
wget 'https://stream.mux.com/02JXvX00rqgwp1artfABOXi9Nnov00lxICy/high.mp4' -O 'Track 01  CoNZealand/Old New Writers.mp4'
wget 'https://stream.mux.com/vPa3KaKkH5f8uWMsjz1yF1SXdN3wATzx/high.mp4' -O 'Track 01  CoNZealand/Great Worlds in SF.mp4'
wget 'https://stream.mux.com/dFuPFrnKUtlsDMLjCMNAITMZgtSF1YkZ/high.mp4' -O 'Track 01  CoNZealand/Climate FictionClimate Fact.mp4'
wget 'https://stream.mux.com/piLhOXWbhnS3E26cOmBH3KWIF004bmIz3/high.mp4' -O 'Track 01  CoNZealand/Access to Space.mp4'
wget 'https://stream.mux.com/oiQlpy6X9698xw7AqrlAKvdmaXxHrwGv/high.mp4' -O 'Track 01  CoNZealand/From Peter Jackson to Taika Waititi New Zealand Originated Genre Films and TV Series.mp4'
wget 'https://stream.mux.com/rZqIOMT47FcKjIP2BgRIttMyvqLqzmDk/high.mp4' -O 'Track 01  CoNZealand/Creating the Doodle.mp4'
wget 'https://stream.mux.com/b7LNDtrHqlJM02J3L1mpoDr68goEUu00EC/high.mp4' -O 'Track 01  CoNZealand/The Ascent of Wonder What Makes Hard SF.mp4'
wget 'https://stream.mux.com/00cnLVleteZ94nagRm8IGO52zlHl02eFqu/high.mp4' -O 'Track 01  CoNZealand/The Decade in Anime.mp4'
wget 'https://stream.mux.com/bJ5GzmJg6h6coswoO5CjBTGXxrhiCstP/high.mp4' -O 'Track 01  CoNZealand/Our New Robot Overlords Why and How They Will Take Over.mp4'
wget 'https://stream.mux.com/702Y5WvX5jpwvrJvZJsrXMPD026Ywx8Lqm/high.mp4' -O 'Track 01  CoNZealand/Urban Fantasy in the 21st Century.mp4'
wget 'https://stream.mux.com/Y5th0102pNIfrTXNPaRM013D2XrwseCmUgx/high.mp4' -O 'Track 01  CoNZealand/Essentials of TARDIS Engineering.mp4'
wget 'https://stream.mux.com/CcevvrHOVZd2Rw6B02bhsf33DvkA9fcmf/high.mp4' -O 'Track 01  CoNZealand/Why We ReadWriteEdit Anthologies.mp4'
wget 'https://stream.mux.com/fx8nwQobH9T026feLkP5koJcf02db88eWY/high.mp4' -O 'Track 01  CoNZealand/Speculative Poetry Deathmatch Thunderdome.mp4'
wget 'https://stream.mux.com/vMtItH02VnUcZz5018IIWNlfx3PFXzASGv/high.mp4' -O 'Track 01  CoNZealand/Quantum Computing Nearing Reality.mp4'
wget 'https://stream.mux.com/SnsHgmFZ2Tm8O6tjSJgq5FlBVoA31CPD/high.mp4' -O 'Track 01  CoNZealand/Sarabande  Resurrection Eve.mp4'
wget 'https://stream.mux.com/Bah02B01tpQbtlmM01aH7Bqls6zxQyW3jut/high.mp4' -O 'Track 01  CoNZealand/Star Wars in Review.mp4'
wget 'https://stream.mux.com/S01zUIJRDz01mJrMDITrgaiT57V2wQOE02n/high.mp4' -O 'Track 01  CoNZealand/TV in Space The Expanse Star Trek The Orville and More.mp4'
wget 'https://stream.mux.com/ZqXaEeibq5gMK6mEY01hamHLrAPct01HQR/high.mp4' -O 'Track 01  CoNZealand/Beyond the Anglosphere SF and Fantasy from the Rest of the World.mp4'
wget 'https://stream.mux.com/36uFgby1dfqXh7myCJfjDt01eBtikmAvm/high.mp4' -O 'Track 01  CoNZealand/The Appeal of SpiderMan.mp4'
mkdir 'Track 05  CoNZealand'
wget 'https://stream.mux.com/a1s7AagOyDNlD4ZtdyQa00tTut00nuBUiK/high.mp4' -O 'Track 05  CoNZealand/Climate Change and Conventions.mp4'
wget 'https://stream.mux.com/8n7oUNVUitRCp6Lq5h8CYMSWum76eRpL/high.mp4' -O 'Track 05  CoNZealand/Running Conventions A Worldwide Perspective.mp4'
wget 'https://stream.mux.com/7dzF6bbcPgjMe22IX4JIl1QE1evMYaAD/high.mp4' -O 'Track 05  CoNZealand/The Death of Genre.mp4'
wget 'https://stream.mux.com/Q933Rc00DD4HYtXZ1KIM3dgcKgEaDqr73/high.mp4' -O 'Track 05  CoNZealand/The Evolution of Fanzines.mp4'
wget 'https://stream.mux.com/fKMcn7VURKjOCGC4rFY8DPFNQ01tX2zIi/high.mp4' -O 'Track 05  CoNZealand/Feedback Session 1.mp4'
wget 'https://stream.mux.com/SgVbhmnxh00e8PycmribzALEoeHvjkfcQ/high.mp4' -O 'Track 05  CoNZealand/Scarey Stuff.mp4'
wget 'https://stream.mux.com/yTBN9iA00Voah6c3S8iWFJnmlFnbWpYq1/high.mp4' -O 'Track 05  CoNZealand/Accessible Yoga.mp4'
wget 'https://stream.mux.com/EOVqKLcXdhQ02j3H2Yjo7aQPyLd8MaXh02/high.mp4' -O 'Track 05  CoNZealand/How Podcasts Are Transforming the Speculative Fiction Landscape.mp4'
wget 'https://stream.mux.com/iaePQk01rqHovhticsV014n1yEKayRuU94/high.mp4' -O 'Track 05  CoNZealand/SF Cons Around the World.mp4'
wget 'https://stream.mux.com/ZCdbiI2miolD6Wime8602401rZSt2DQfac/high.mp4' -O 'Track 05  CoNZealand/My Favourite Board Game.mp4'
wget 'https://stream.mux.com/DNG2txH86NU2hYqz5a4niA95ctJQYrxJ/high.mp4' -O 'Track 05  CoNZealand/Narrative Imagery.mp4'
wget 'https://stream.mux.com/01OpNm5xvE6eHvPQvleED301lSNCxa5qJJ/high.mp4' -O 'Track 05  CoNZealand/1001 Years Later What Happened to Arabian Fiction.mp4'
wget 'https://stream.mux.com/mE6n7cR00bPYqb2sB6k01k4p6Q3d01wLl1j/high.mp4' -O 'Track 05  CoNZealand/History of SF Fandom in New Zealand.mp4'
wget 'https://stream.mux.com/hMqv02uU2n5I1hZ5eF8kO7E64h4UkW02io/high.mp4' -O 'Track 05  CoNZealand/Technology for Disability in the Real World and in Speculative Fiction.mp4'
wget 'https://stream.mux.com/Aym9rnAqQGLwXhZv9gAHVOT7YImBw8e1/high.mp4' -O 'Track 05  CoNZealand/LGBTQIA Themes in Books Comics and MoviesTV.mp4'
wget 'https://stream.mux.com/YcvlmRKTSmP5aDp02IjG02gufAHgkkLQQ6/high.mp4' -O 'Track 05  CoNZealand/Friends Dont Let Friends Run Worldcons.mp4'
wget 'https://stream.mux.com/MxA00CK00Nxaj02uebtBOC6TwZmnpsnx3Zy/high.mp4' -O 'Track 05  CoNZealand/Art for Children.mp4'
wget 'https://stream.mux.com/g5isjYTMa4xTGjP3OQB00MF5uFF9E00n8d/high.mp4' -O 'Track 05  CoNZealand/Fandom Over the Years  The Female Perspective.mp4'
wget 'https://stream.mux.com/q02H2akqsBnWa7v7GNfT1WvSbF9qXv2Rm/high.mp4' -O 'Track 05  CoNZealand/Good Omens at 30.mp4'
wget 'https://stream.mux.com/VXA2z4UE42kIPU5263oSL501pdQ01d9y00U/high.mp4' -O 'Track 05  CoNZealand/Pandemic Myths and Facts.mp4'
wget 'https://stream.mux.com/TaHeeQR0101FSxxYtjJsAZZxgRxj88j2tL/high.mp4' -O 'Track 05  CoNZealand/Universal Rights in the Age of AI.mp4'
wget 'https://stream.mux.com/4kTnXqTuy02014Q2mPy9xI9s6GVSIbXPTE/high.mp4' -O 'Track 05  CoNZealand/Feedback Session 3.mp4'
wget 'https://stream.mux.com/pXFNiTYXTxyX02S00gKealAz4WZE013kGH00/high.mp4' -O 'Track 05  CoNZealand/Horror from Elsewhere.mp4'
wget 'https://stream.mux.com/KyhtsIL017L00EUvHY6G6Mbhj600egDG026u/high.mp4' -O 'Track 05  CoNZealand/Fandom in the 1970s.mp4'
wget 'https://stream.mux.com/rfzQ01NaO01vcqJB01hLdDm7ZdFSp8SubN7/high.mp4' -O 'Track 05  CoNZealand/GOH  Tea with Rose Mitchell.mp4'
wget 'https://stream.mux.com/yvFOy1k2eby97OX3s2MBP8LERZoCCOlI/high.mp4' -O 'Track 05  CoNZealand/History of SF Fandom in Australia.mp4'
wget 'https://stream.mux.com/7EAJJOPMFBVDaRyyYrCjusMA0101AL6W2B/high.mp4' -O 'Track 05  CoNZealand/Feedback Session 4.mp4'
wget 'https://stream.mux.com/UHHD9UDG4012SnIXEYt7iWpOm33gDvOEI/high.mp4' -O 'Track 05  CoNZealand/Pubquiz.mp4'
wget 'https://stream.mux.com/QyVjen9s0000lPKij01bZU12lR6wfl1sixo/high.mp4' -O 'Track 05  CoNZealand/New Zealand Fandom Today.mp4'
wget 'https://stream.mux.com/Nyst62Cd02r66idfFqUqn2JI602Bzj6Wf7/high.mp4' -O 'Track 05  CoNZealand/These Old Shades If Georgette Heyer Wrote a Ghost Story.mp4'
wget 'https://stream.mux.com/clsYaOv5SretooH01pcQtBT00gkdLaRvRw/high.mp4' -O 'Track 05  CoNZealand/Ghosts in the Ships Sentient Ships in SF and Fantasy.mp4'
wget 'https://stream.mux.com/KxYrtMi2XTrpbxHhq96Pp01gsuelbCv7t/high.mp4' -O 'Track 05  CoNZealand/What Fanfiction Can Teach Genre Writers.mp4'
wget 'https://stream.mux.com/OXZvg4IbdBb01siCQbxTa97OvOk7DWtG01/high.mp4' -O 'Track 05  CoNZealand/Freedom in SF Forty Years of the Prometheus Awards.mp4'
wget 'https://stream.mux.com/MrcuFx6xfxj3MEP53kAQNTIDD6CE4e1I/high.mp4' -O 'Track 05  CoNZealand/The Future of the Marvel Cinematic Universe.mp4'
wget 'https://stream.mux.com/kNyotVPRmK1bIRTsuQknzUjzhjxePkkT/high.mp4' -O 'Track 05  CoNZealand/Feedback Session 5  Into the Future.mp4'
